name: Create Infra AWS Academy

on:
  push:
    branches: [ master ]

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "eks-fiap-2024"

jobs:
  deploy:
    name: Deploy AWS Academy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: AWS Configuration
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.REGION_DEFAULT }}

    - name: Update Kubernetes Cluster
      run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION_DEFAULT }}

    - name: Update Kube Config
      run: |
        kubectl apply -f k8s/eks-deployment.yaml
        kubectl apply -f k8s/eks-svc.yaml

